name: 'redshift'
version: '0.0.1'

source-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  redshift:
    base:
      materialized: ephemeral

    introspection:
      materialized: ephemeral

    views:
      materialized: view
